### ISSUE TITLE
s3: setting region issues

### ISSUE THREAD

**Issue by tomholford** [urbit/garden#27]
IIRC there's another issue re: `bad-key` when setting region in garden, now hearing about this one:

![image](https://user-images.githubusercontent.com/16504501/208182706-c3fd9da9-8c62-4c71-b9dc-eacc1e780700.png)

**Comment by jamesacklin** [comment]
@patosullivan Do we have changes to support this in %s3-store and %garden that are waiting to be deployed?

**Comment by lukestiles** [comment]
Another repro here /1/chan/chat/~dopzod/urbit-help/msg/~minweb-datsyt/170.141.184.505.988.662.262.375.892.519.415.546.118

**Comment by arthyn** [comment]
the region changes were made in urbit/urbit for s3-store which lives in old groups. these changes never made it to master there so they were never deployed. the form in garden depends on those changes. so we need to deploy %landscape with those changes.
